spring:
  config:
    import: classpath:secrets.yml

server:
  servlet:
    context-path: /api
  port: 5000

app:
  #DataSource Configuration
  datasource:
    jdbc-url: jdbc:postgresql://${database-config.url-database}/petsystem
    username: ${database-config.username-database}
    password: ${database-config.password-database}
    pool-size: 30