CREATE TABLE IF NOT EXISTS types (
  id UUID PRIMARY KEY NOT NULL,
  name TEXT NOT NULL UNIQUE
);
CREATE INDEX ON types (name);
CREATE TABLE IF NOT EXISTS pets (
  id UUID PRIMARY KEY NOT NULL,
  type_id UUID NOT NULL REFERENCES types(id),
  name TEXT NOT NULL UNIQUE,
  birth_date DATE
);
CREATE INDEX ON pets (name);